### PR TITLE
fix(build): Issue 21 -- fix build path and declare typings

### PR DESCRIPTION
**Pull request by avhetman**
Fixes https://github.com/Comcast/scte35-js/issues/21

### CODE REVIEW

**Comment by avhetman** [comment]
This CLA sure takes some time to process.... sigh

**Comment by estobbart** [comment]
It should be almost immediate.. you may want to try it again.

**Comment by avhetman** [comment]
When I tried to do it again, it just shows me the agreement that I already filled out with all the fields grayed out and immutable. Seems that it should be all good on my end, but who knows.

**Comment by kristakhare** [comment]
Hi there - the CLA assistant gets hung up when it can't verify an email address.
There is at least 1 commit in the PR associated with an email address that is not associated with the avhetman username. @avhetman perhaps you can add whatever email address you used in your commits as a secondary email address to your GH account and check again? If that still doesn't work I say @estobbart should go ahead and merge, you can override it as a repo admin.

**Comment by estobbart** [comment]
@kristakhare thanks! @avhetman is a Comcast employee. Is there a way to add him to a CLA whitelist? Or does it mean adding that email as a secondary?

**Comment by kristakhare** [comment]
@JohnRiv periodically adds members of the Comcast Github org to the whitelist, so next time that exercise is done, Andrei's name should be captured. Thank you!

**Comment by JohnRiv** [comment]
@avhetman thank you for your contribution! Sorry our CLA tool has a limitation where it is tied to GitHub usernames instead of email addresses. The email address associated with your commits in this PR is not associated with your GitHub account (or any GitHub account for that matter). When you make your next contribution, please be sure the commits are tied to an email address associated with your GitHub account. Thanks!

**Comment by JohnRiv** [comment]
> @kristakhare thanks! @avhetman is a Comcast employee. Is there a way to add him to a CLA whitelist? Or does it mean adding that email as a secondary?

Adding his Comcast email as a secondary is the easiest option

**Pull request merged**
